name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Routing
  go_router: ^17.1.0

  # Firebase
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_storage: ^13.0.6
  firebase_analytics: ^12.1.2
  firebase_crashlytics: ^5.0.7
  firebase_messaging: ^16.1.1

  # Dependency injection
  get_it: ^9.2.0
  injectable: ^2.5.0

  # Functional programming
  dartz: ^0.10.1

  # Network
  connectivity_plus: ^7.0.0

  # Code generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 0.14.4
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  freezed: ^3.0.0
  json_serializable: ^6.9.4
  package_rename: 1.10.1

flutter:
  uses-material-design: true

scripts: derry.yaml
